Repository openstreetmap/id-tagging-schema, pull requests merged in 2021-12, with the labels that each got.

#280 add highchair field to cafe,fast_food,restaurant
  data/fields/highchair.json
  data/presets/amenity/cafe.json
  data/presets/amenity/fast_food.json
  data/presets/amenity/restaurant.json
Labels: enhancement

#212 Avoid snake_case on traffic_sign and cycle_network
  data/fields/cycle_network.json
  data/fields/traffic_sign.json
Labels: bug

#199 add locked field to lockable barriers
  data/fields/locked.json
  data/presets/barrier/chain.json
  data/presets/barrier/gate.json
  data/presets/barrier/lift_gate.json
Labels: enhancement

#194 add fields for level crossing
  data/fields/crossing/barrier.json
  data/fields/crossing/bell.json
  data/fields/crossing/light.json
  data/presets/railway/crossing.json
  data/presets/railway/level_crossing.json
  interim/source_strings.yaml
Labels: enhancement

#107 Adapt `capacity` tags for camp sites etc.
  data/fields/capacity/caravans.json
  data/fields/capacity/persons.json
  data/fields/capacity/tents.json
  data/presets/tourism/camp_site.json
  data/presets/tourism/caravan_site.json
Labels: enhancement, new-field

#83 Add youth center
  data/presets/amenity/community_centre/youth_centre.json
Labels: new-preset

#73 Add parking=street_side
  data/fields/parking.json
  data/fields/parking/orientation.json
  data/presets/amenity/parking/street-side.json
  interim/source_strings.yaml
Labels: enhancement, new-preset

#297 upgrade path for amenity=youth_centre
  data/deprecated.json
Labels: deprecating

#216 Add Expressway field to Trunk and Primary Road presets
  data/fields/expressway.json
  data/presets/highway/primary.json
  data/presets/highway/trunk.json
  interim/source_strings.yaml
Labels: regional, new-field
