Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-05, with the labels that each got.

#414 Add Trolley Bay preset and `trolley:deposit` field
  data/fields/deposit/trolley.json
  data/presets/amenity/trolley_bay.json
Labels: new-preset

#417 add name field to beach preset
  data/presets/natural/beach.json
Labels: add-field

#418 Add basic tag position to fire_hydrant
  data/fields/fire_hydrant/position.json
  data/presets/emergency/fire_hydrant.json
Labels: new-field

#425 Update wastewater_plant.json
  data/presets/man_made/wastewater_plant.json
Labels: add-field

#438 Add opening_hours to parcel_locker
  data/presets/amenity/parcel_locker.json
Labels: add-field

#441 Add Tetherball Court preset
  data/presets/leisure/pitch/tetherball.json
Labels: new-preset

#445 Add Padel Court preset
  data/presets/leisure/pitch/padel.json
  interim/source_strings.yaml
Labels: new-preset

#446 Fix typo
  data/presets/playground/springy.json
Labels: new-term

#453 Additional fields for `crossing=traffic_signals` presets
  data/fields/button_operated.json
  data/fields/traffic_signals/arrow.json
  data/fields/traffic_signals/countdown.json
  data/fields/traffic_signals/minimap.json
  data/fields/traffic_signals/sound.json
  data/fields/traffic_signals/vibration.json
  data/presets/highway/crossing/signals.json
  data/presets/highway/footway/signals.json
Labels: new-field

#452 Add man_made=carpet_hanger
  data/presets/man_made/carpet_hanger
Labels: new-preset

#458 Add area to parcel_locker
  data/presets/amenity/parcel_locker.json
Labels: bug

#455 Set common tags for trees
  data/fields/diameter_crown.json
  data/fields/genus.json
  data/fields/species.json
  data/fields/taxon.json
  data/presets/natural/tree.json
Labels: new-field, add-field

#449 Add flashing_lights field
  data/fields/flashing_lights.json
  data/presets/highway/crossing/marked.json
  data/presets/highway/crossing/unmarked.json
  data/presets/highway/footway/marked.json
  data/presets/highway/footway/unmarked.json
Labels: considering, new-field

#427 Add some more values to beauty=*
  data/fields/beauty.json
Labels: new-value

#337 new deprecation: building:roof:shape -> roof:shape
  data/deprecated.json
Labels: deprecating

#327 change default highway value for golf cart paths to "path"
  data/fields/highway_cartpath.json
  data/presets/golf/cartpath.json
  data/presets/golf/path.json
  interim/source_strings.yaml
Labels: enhancement

#288 rename highway=track preset
  data/presets/highway/track.json
  interim/source_strings.yaml
Labels: considering
