Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-02, with the labels that each got.

#380 add ref & website fields to monitoring station
  data/presets/man_made/monitoring_station.json
Labels: add-field

#381 add rail as a term for Train Track
  data/presets/railway/rail.json
Labels: new-term

#382 update lifeboat station preset
  data/fields/seamark/rescue_station/category.json
  data/presets/emergency/lifeboat_station.json
Labels: new-field, new-term

#326 add "customers" option to access field(s)
  data/fields/access.json
  interim/source_strings.yaml
Labels: new-value

#385 Add Four Square Court preset
  data/presets/leisure/pitch/four_square.json
Labels: new-preset

#391 Fix data/presets/amenity/ticket_validator format
  data/presets/amenity/ticket_validator.json
  data/presets/disc_golf/basket.json
  data/presets/disc_golf/tee.json
  data/presets/emergency/water_reservoir_covered.json
  interim/source_strings.yaml
Labels: bug

#400 more and better recycling terms
  data/fields/recycling_accepts.json
Labels: new-value

#407 Add Lighting Mast preset
  data/presets/man_made/mast/lighting.json
Labels: new-preset
