Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-12, with the labels that each got.

#662 fix confusing crane presets
  data/fields/crane/type.json
Labels: new-value

#664 add preset for office=graphic_design
  data/presets/office/graphic_design.json
Labels: new-preset

#663 add seamark tags to marine fuel & sewerage presets
  data/presets/waterway/fuel.json
  data/presets/waterway/sanitary_dump_station.json
Labels: enhancement

#665 add direction field to some presets
  data/presets/aeroway/holding_position.json
  data/presets/playground/roundabout.json
  data/presets/railway/derail.json
  data/presets/shop/car_repair.json
Labels: add-field

#666 add preset for Variable Message Sign
  data/presets/traffic_sign/variable_message.json
Labels: new-preset

#694 Update waste_disposal.json
  data/presets/amenity/waste_disposal.json
Labels: new-label

#693 Update tanning.json
  data/presets/shop/beauty/tanning.json
Labels: new-label

#692 Add translatable strings to craft type field
  data/fields/craft.json
Labels: new-label

#695 Update craft.json
  data/fields/craft.json
Labels: bug

#696 Add Mobile Home Park preset
  data/presets/landuse/residential/trailer_park.json
Labels: new-preset

#697 Add `drive_through` field to Cafe preset
  data/presets/amenity/cafe.json
  data/presets/amenity/fast_food.json
  data/presets/amenity/restaurant.json
Labels: add-field

#698 Add `operator:type` field to park related presets
  data/presets/leisure/nature_reserve.json
  data/presets/leisure/park.json
  data/presets/leisure/sports_centre.json
Labels: add-field

#705 Add terms to Splashpad preset
  data/presets/playground/splash_pad.json
Labels: new-label

#700 Add translatable strings to artwork_type field
  data/fields/artwork_type.json
Labels: new-value

#701 Add translatable strings to board_type field
  data/fields/board_type.json
Labels: new-value

#702 Add translatable strings to bollard type field
  data/fields/bollard.json
Labels: new-value
