Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-08, with the labels that each got.

#554 Disable TagInfo-suggestions of parking:orientation
  data/fields/parking/orientation.json
Labels: bug

#557 remove landuse=industrial default
  data/presets/power/plant/source/hydro.json
Labels: bug

#560 Use "ski" instead of "Ski" in activity field
  data/fields/activity.json
Labels: bug

#561 Cemetery Section: use `name` instead of `sector:name`
  data/fields/sector/name.json
  data/presets/cemetery/sector.json
Labels: add-field

#562 Add `turning_circle` field
  data/fields/turning_circle.json
  data/presets/highway/turning_circle.json
Labels: new-field

#475 Add aliases and terms for `shop=*` presets
  data/presets/amenity/fast_food/sandwich.json
  data/presets/shop/antiques.json
  data/presets/shop/bookmaker.json
  data/presets/shop/books.json
  data/presets/shop/butcher.json
  data/presets/shop/car.json
  data/presets/shop/car_repair.json
  data/presets/shop/clothes/underwear.json
  data/presets/shop/confectionery.json
  data/presets/shop/convenience.json
  data/presets/shop/copyshop.json
  data/presets/shop/country_store.json
  data/presets/shop/deli.json
  data/presets/shop/funeral_directors.json
  data/presets/shop/games.json
  data/presets/shop/garden_centre.json
  data/presets/shop/general.json
  data/presets/shop/gift.json
  data/presets/shop/greengrocer.json
  data/presets/shop/hairdresser.json
  data/presets/shop/hairdresser_supply.json
  data/presets/shop/hardware.json
  data/presets/shop/health_food.json
  data/presets/shop/herbalist.json
  data/presets/shop/houseware.json
  data/presets/shop/jewelry.json
  data/presets/shop/kiosk.json
  data/presets/shop/laundry/self_service.json
  data/presets/shop/mall.json
  data/presets/shop/model.json
  data/presets/shop/money_lender.json
  data/presets/shop/motorcycle_repair.json
  data/presets/shop/musical_instrument.json
  data/presets/shop/newsagent.json
  data/presets/shop/nutrition_supplements.json
  data/presets/shop/pawnbroker.json
  data/presets/shop/pet.json
  data/presets/shop/seafood.json
  data/presets/shop/second_hand.json
  data/presets/shop/stationery.json
  data/presets/shop/ticket.json
  data/presets/shop/toys.json
  data/presets/shop/variety_store.json
Labels: new-label
