Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-09, with the labels that each got.

#570 Add 'package locker' alias for Parcel Locker preset
  data/presets/amenity/parcel_locker.json
Labels: new-label

#559 Gas Station preset: move `building` field to `fields`
  data/presets/amenity/fuel.json
Labels: add-field

#567 Update bbq.json to allow area
  data/presets/amenity/bbq.json
Labels: bug

#575 add gender field on hairdresser
  data/presets/shop/hairdresser.json
Labels: add-field

#579 Update icon for Nursery/Childcare preset
  data/presets/amenity/childcare.json
Labels: new-icon

#580 Add Runaway Truck Ramp preset
  data/presets/highway/escape.json
Labels: new-preset, new-field

#583 describe tracktype=grade1 as paved only
  data/fields/tracktype.json
Labels: bug, new-label

#592 also catch internet_access=wi-fi and WLAN
  data/deprecated.json
Labels: deprecating

#593 Create catenary_mast.json
  data/presets/power/catenary_mast.json
Labels: new-preset

#470 move aliases of `highway=track` from terms to aliases field
  data/presets/highway/track.json
  interim/source_strings.yaml
Labels: new-label
