Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-01, with the labels that each got.

#227 Add layer=1 to building=roof preset
  data/presets/building/roof.json
Labels: enhancement

#309 Create gynaecology.json
  data/presets/amenity/doctors/gynaecology.json
Labels: new-preset

#304 Added Police Checkpoint
  data/presets/police/checkpoint
Labels: new-preset

#320 Add field `species:wikidata` to plant objects
  data/presets/barrier/hedge.json
  data/presets/natural/scrub.json
  data/presets/natural/tree_row.json
  data/presets/natural/wood.json
Labels: new-field

#136 Add capacity for childcare and kindergarten
  data/presets/amenity/childcare.json
  data/presets/amenity/kindergarten.json
  data/presets/amenity/school.json
Labels: considering

#329 add Footway Area area:highway label
  data/presets/area/footway.json
Labels: new-preset

#334 Add "sport field" as synonym to "Sport pitch"
  data/presets/leisure/pitch.json
Labels: new-term

#335 "key duplication" to synonyms of craft=key_cutter
  data/presets/craft/key_cutter.json
Labels: new-term

#339 Parcel locker category change
  data/deprecated.json
  data/fields/parcel_dropoff.json
  data/fields/parcel_pickup.json
  data/presets/amenity/parcel_locker.json
  data/presets/amenity/vending_machine/parcel_pickup_dropoff.json
Labels: deprecating, new-preset, add-field

#341 embassy=embassy to embassy=yes (new deprecation)
  data/deprecated.json
Labels: deprecating

#343 specify values for "embassy" tag
  data/deprecated.json
  data/fields/embassy.json
  interim/source_strings.yaml
Labels: help wanted, deprecating, new-value

#342 Add direction field to benches
  data/presets/amenity/bench.json
Labels: add-field

#346 Add `smoothness` to `fields` for cycleway, bicycle_foot, crossing/bicycle_foot
  data/presets/highway/cycleway.json
  data/presets/highway/cycleway/bicycle_foot.json
  data/presets/highway/cycleway/crossing/bicycle_foot.json
Labels: add-field

#350 Add strings to castle_type.json
  data/fields/castle_type.json
Labels: new-value

#349 Add strings to recycling_accepts.json
  data/fields/recycling_accepts.json
Labels: new-value

#355 Add `bin` field to `vending=excrement_bags`
  data/presets/amenity/vending_machine/excrement_bags.json
Labels: add-field

#367 Add Futsal Court preset
  data/presets/leisure/pitch/futsal.json
Labels: new-preset

#371 Change icon for Swamp preset
  data/presets/natural/wetland/swamp.json
Labels: new-icon

#369 Add Archery Range preset
  data/presets/leisure/pitch/archery.json
Labels: new-preset

#372 Add more disc golf features
  data/fields/ref_disc_golf_hole.json
  data/presets/disc_golf/basket.json
  data/presets/disc_golf/hole.json
  data/presets/disc_golf/tee.json
Labels: new-preset

#375 Avoid snake-casing network
  data/fields/network_road.json
Labels: bug
