Repository openstreetmap/id-tagging-schema, pull requests merged in 2022-10, with the labels that each got.

#603 Add Fire Station Building preset
  data/presets/building/fire_station.json
Labels: new-preset

#600 Add field for `building:prefabricated`
  data/fields/building/prefabricated.json
  data/presets/building.json
Labels: new-field

#608 add descriptions of bicycle parkings
  data/fields/bicycle_parking.json
Labels: new-label

#614 Allow Jersey Barrier preset on vertexes instead of points
  data/presets/barrier/jersey_barrier.json
Labels: bug

#613 Add preset Cafeteria
  data/presets/amenity/fast_food/cafeteria.json
  interim/source_strings.yaml
Labels: new-preset

#598 upgrade to schema-builder v5
  data/fields/address.json
  data/fields/building/levels_building.json
  data/fields/colour.json
  data/fields/contact/webcam.json
  data/fields/ele.json
  data/fields/ele_node.json
  data/fields/note.json
  data/fields/payment_multi_fee.json
  data/fields/phone.json
  data/fields/restrictions.json
  data/fields/source.json
  data/fields/website.json
  data/fields/wheelchair.json
  data/fields/wikidata.json
  data/fields/wikipedia.json
  data/presets/highway/motorway_link-US-CA.json
  data/presets/highway/primary_link-US-CA.json
  data/presets/highway/trunk_link-US-CA.json
  interim/source_strings.yaml
  package.json
  scripts/build.js
  scripts/dist.js
  scripts/test.js
Labels: schema

#164 Add `highway=busway` preset
  data/deprecated.json
  data/presets/highway/busway.json
Labels: new-preset

#251 Add translatable tunnel types
  data/fields/tunnel_combo.json
  interim/source_strings.yaml
Labels: new-value

#257 Translatable strings for crops
  data/fields/crop.json
  interim/source_strings.yaml
Labels: new-label

#261 Add Population Date and Population Source fields
  data/fields/population.json
  data/fields/population/date.json
  data/fields/source/population.json
  data/presets/amenity/refugee_site.json
  data/presets/place/city.json
  data/presets/place/hamlet.json
  data/presets/place/neighbourhood.json
  data/presets/place/quarter.json
  data/presets/place/suburb.json
  data/presets/place/town.json
  data/presets/place/village.json
  interim/source_strings.yaml
Labels: new-field

#392 Update speciality.json
  data/fields/healthcare/speciality.json
Labels: new-value

#144 add reservoir_type=tailings
  data/deprecated.json
Labels: deprecating

#263 Add translatable strings for Religion field
  data/fields/religion.json
  interim/source_strings.yaml
Labels: new-value

#325 add toilets field as optional field of more POI presets
  data/fields/toilets/wheelchair.json
  data/presets/amenity/cafe.json
  data/presets/amenity/pub.json
  data/presets/amenity/restaurant.json
  data/presets/shop.json
  data/presets/tourism/aquarium.json
  data/presets/tourism/gallery.json
  data/presets/tourism/information/office.json
  data/presets/tourism/museum.json
  data/presets/tourism/zoo.json
  interim/source_strings.yaml
Labels: new-field, add-field

#521 Add Bike and Ride field
  data/fields/bike_ride.json
  data/presets/amenity/bicycle_parking.json
Labels: new-field

#463 add preset for highway=service mapped as areas
  data/presets/highway/service_area.json
Labels: new-preset

#618 Add terms to bed, clothes and wedding shops
  data/presets/shop/bed.json
  data/presets/shop/clothes.json
  data/presets/shop/clothes/wedding.json
Labels: new-label

#620 generator:method=solar -> generator:source=solar
  data/deprecated.json
Labels: deprecating

#622 Add presets for `office=property_mangagement` and `office=union`
  data/presets/office/property_management.json
  data/presets/office/union.json
Labels: new-preset

#625 Add community_centre:for LGBTQ+ Community Center
  data/presets/amenity/community_centre/lgbtq.json
Labels: enhancement
