Repository openstreetmap/id-tagging-schema, pull requests merged in 2023-04, with the labels that each got.

#853 Add translatable strings to dock field
  data/fields/dock.json
Labels: new-value

#852 Add translatable strings to collector field
  data/fields/collector.json
Labels: new-value

#837 Enable tagging unspecific crossing
  data/presets/highway/_crossing.json
  data/presets/highway/crossing.json
Labels: enhancement

#860 survey_date and date:survey -> survey:date
  data/deprecated.json
Labels: deprecating

#862 Add "kerb" tag as an optional field to crossings
  data/presets/barrier/kerb/flush.json
  data/presets/barrier/kerb/lowered.json
  data/presets/barrier/kerb/raised.json
  data/presets/barrier/kerb/rolled.json
  data/presets/highway/crossing.json
  data/presets/highway/crossing/_marked.json
  data/presets/highway/crossing/traffic_signals.json
  data/presets/highway/crossing/uncontrolled.json
  data/presets/highway/crossing/unmarked.json
  interim/source_strings.yaml
Labels: bug, add-field

#859 Add contact:facebook field
  data/fields/contact/facebook.json
  data/presets/amenity/animal_boarding.json
  data/presets/amenity/animal_breeding.json
  data/presets/amenity/animal_shelter.json
  data/presets/amenity/arts_centre.json
  data/presets/amenity/bank.json
  data/presets/amenity/bar.json
  data/presets/amenity/boat_rental.json
  data/presets/amenity/bureau_de_change.json
  data/presets/amenity/cafe.json
  data/presets/amenity/car_rental.json
  data/presets/amenity/car_wash.json
  data/presets/amenity/casino.json
  data/presets/amenity/cinema.json
  data/presets/amenity/clinic.json
  data/presets/amenity/college.json
  data/presets/amenity/community_centre.json
  data/presets/amenity/dentist.json
  data/presets/amenity/dive_centre.json
  data/presets/amenity/doctors.json
  data/presets/amenity/dojo.json
  data/presets/amenity/driving_school.json
  data/presets/amenity/fast_food.json
  data/presets/amenity/food_court.json
  data/presets/amenity/fuel.json
  data/presets/amenity/hospital.json
  data/presets/amenity/library.json
  data/presets/amenity/nightclub.json
  data/presets/amenity/pub.json
  data/presets/amenity/restaurant.json
  data/presets/amenity/stripclub.json
  data/presets/amenity/theatre.json
  data/presets/club.json
  data/presets/craft.json
  data/presets/leisure/amusement_arcade.json
  data/presets/leisure/bowling_alley.json
  data/presets/leisure/fitness_centre.json
  data/presets/leisure/golf_course.json
  data/presets/leisure/resort.json
  data/presets/leisure/sports_centre.json
  data/presets/leisure/swimming_pool.json
  data/presets/shop.json
  data/presets/tourism/alpine_hut.json
  data/presets/tourism/apartment.json
  data/presets/tourism/chalet.json
  data/presets/tourism/guest_house.json
  data/presets/tourism/motel.json
  data/presets/tourism/museum.json
  data/presets/tourism/theme_park.json
  data/presets/tourism/zoo.json
Labels: new-field

#864 match "white goods" to shop=appliance
  data/presets/shop/appliance.json
Labels: new-label

#865 "Pedestrian Island" should find `footway=traffic_island`
  data/presets/highway/footway/traffic_island.json
Labels: new-label

#857 add some popular cuisine values
  data/fields/cuisine.json
  data/presets/amenity/restaurant/georgian.json
  data/presets/amenity/restaurant/ukrainian.json
Labels: new-value

#868 Improve search term in horse_riding preset
  data/presets/leisure/horse_riding.json
Labels: new-label

#867 more appropriate terms for ad devices
  data/presets/advertising/board.json
  data/presets/advertising/column.json
  data/presets/advertising/poster_box.json
  data/presets/advertising/totem.json
Labels: new-label

#872 more terms for pulmonology
  data/presets/amenity/doctors/pulmonology.json
Labels: new-label

#873 Additional synonym and a better name for gynecologist
  data/presets/amenity/doctors/gynaecology.json
  interim/source_strings.yaml
Labels: new-label

#884 stop assuming that all shop=organic are supermarkets
  data/deprecated.json
Labels: deprecating

#881 Add Frozen Yogurt Shop preset
  data/presets/amenity/ice_cream/frozen_yogurt.json
Labels: new-preset

#890 Add "bus terminal" term to bus station preset
  data/presets/public_transport/station_bus.json
Labels: new-label

#892 Fix typo in Chicken Wings Fast Food
  data/presets/amenity/fast_food/wings.json
Labels: bug
