Repository openstreetmap/id-tagging-schema, pull requests merged in 2023-02, with the labels that each got.

#774 Add preset for shop=nuts
  data/presets/shop/nuts.json
Labels: new-preset

#773 Add more fields to highway=rest_area
  data/presets/highway/rest_area.json
Labels: add-field

#788 Fix typo
  data/fields/clothes.json
  interim/source_strings.yaml
Labels: bug

#786 Move `access_simple` to main fields for AEDs
  data/presets/emergency/defibrillator.json
Labels: add-field

#775 Create staircase.json
  data/presets/entrance/staircase.json
Labels: new-preset

#780 Add terms (polo/rodeo) for sport=equestrian preset
  data/presets/leisure/pitch/equestrian.json
Labels: new-label

#781 add field for ref:linz:place_id
  data/fields/ref/linz/place_id-NZ.json
  interim/source_strings.yaml
Labels: new-field

#782 add railway route to categories file
  data/preset_categories/route.json
Labels: enhancement

#785 allow advertising presets as a line & add `message` field
  data/fields/message.json
  data/presets/advertising/poster_box.json
  data/presets/advertising/totem.json
Labels: bug, new-field

#787 Add Senior Assisted Living Facility preset
  data/presets/amenity/social_facility/assisted_living.json
Labels: new-preset

#777 Update deprecated.json
  data/deprecated.json
Labels: deprecating

#790 make clear that is for pet groomer
  data/presets/shop/pet_grooming.json
Labels: new-label

#784 create preset for a Depot
  data/fields/depot.json
  data/presets/landuse/industrial/depot.json
Labels: new-preset, new-field

#648 This add amenity=stripclub
  data/presets/amenity/stripclub.json
Labels: new-preset

#794 Rename psychatrist.json to psychiatrist.json
  data/presets/amenity/doctors/psychiatrist.json
Labels: bug

#796 Add deprecated values of cycleway
  data/deprecated.json
Labels: deprecating

#795 Add Dialysis Center preset
  data/presets/amenity/clinic/dialysis.json
Labels: new-preset

#802 list some projects where it is also used
  README.md
Labels: documentation
