Repository openstreetmap/id-tagging-schema, pull requests merged in 2023-12, with the labels that each got.

#1064 Add "contact/facebook" to "moreFields" in leisure/horse_riding.json
  data/presets/leisure/horse_riding.json
Labels: add-field

#1020 Add preset `man_made=insect_hotel`
  data/presets/man_made/insect_hotel.json
Labels: new-preset

#1069 add preset for `highway=cyclist_waiting_aid`
  data/fields/count.json
  data/fields/footrest.json
  data/fields/handrest.json
  data/fields/side.json
  data/presets/highway/cyclist_waiting_aid.json
Labels: new-preset, new-field

#985 Add roller coaster presets
  data/fields/roller_coaster/track.json
  data/presets/attraction/water_slide.json
  data/presets/roller_coaster/station.json
  data/presets/roller_coaster/support.json
  data/presets/roller_coaster/track.json
Labels: new-preset

#989 Support area for attraction=big_wheel preset
  data/presets/attraction/big_wheel.json
Labels: bug

#998 air compressor alias for amenity=compressed_air
  data/presets/amenity/compressed_air.json
Labels: new-label

#1072 Add "bee hotel" term to insect hotel preset
  data/presets/man_made/insect_hotel.json
Labels: new-label

#1007 Disallow leading zeros in gnis:feature_id
  data/fields/gnis/feature_id-US.json
Labels: enhancement

#1005 add support & colour tags to amenity=letter_box
  data/presets/amenity/letter_box.json
Labels: add-field

#1018 Readme: add link to the schema-builder
  README.md
Labels: documentation

#1030 Specify crossing:markings in Poland
  data/fields/crossing/markings-PL.json
  data/fields/crossing/markings.json
  data/fields/crossing/markings_yes-PL.json
  data/fields/crossing/markings_yes.json
  data/presets/@templates/crossing/markings.json
  data/presets/@templates/crossing/markings_yes.json
Labels: regional, field

#1000 Add ref:edubase
  data/fields/ref/edubase-GB.json
  data/presets/amenity/college.json
  data/presets/amenity/kindergarten.json
  data/presets/amenity/school.json
Labels: regional, new-field

#999 Add field for `opening_hours:drive_through=*`
  data/fields/opening_hours/drive_through.json
  data/presets/amenity/bank.json
  data/presets/amenity/cafe.json
  data/presets/amenity/fast_food.json
  data/presets/amenity/ice_cream.json
  data/presets/amenity/pharmacy.json
  data/presets/shop/alcohol.json
Labels: new-field

#1038 Rename `vending=sweets` preset
  data/presets/amenity/vending_machine/food/snacks.json
  data/presets/amenity/vending_machine/sweets.json
Labels: bug, considering, new-preset, new-label

#1074 Change name `Traffic island` -> `Traffic calming (island)`
  data/fields/traffic_calming.json
  data/presets/traffic_calming/island.json
Labels: bug, new-label
