Repository openstreetmap/id-tagging-schema, pull requests merged in 2023-01, with the labels that each got.

#708 resource label is "presets" not "preset"
  README.md
Labels: documentation

#712 Add translatable strings to social_facility type field
  data/fields/social_facility.json
Labels: new-value

#714 Create preset for residential garden
  data/presets/leisure/garden/residential.json
Labels: new-preset

#731 add most popular alternative medicine practitioners
  data/presets/healthcare/alternative.json
  data/presets/healthcare/alternative/acupuncture.json
  data/presets/healthcare/alternative/ayurveda.json
  data/presets/healthcare/alternative/chiropractic.json
  data/presets/healthcare/alternative/homeopathy.json
  data/presets/healthcare/alternative/naturopathy.json
  data/presets/healthcare/alternative/osteopathy.json
  data/presets/healthcare/alternative/traditional_chinese_medicine.json
Labels: new-preset

#732 Default values for crossing:markings tag for new and existing crossings
  data/fields/crossing/markings_yes.json
  data/presets/highway/crossing/_marked.json
  data/presets/highway/crossing/_zebra.json
  data/presets/highway/crossing/traffic_signals.json
  data/presets/highway/crossing/uncontrolled.json
  data/presets/highway/crossing/unmarked.json
  data/presets/highway/cycleway/crossing/_marked.json
  data/presets/highway/cycleway/crossing/traffic_signals.json
  data/presets/highway/cycleway/crossing/uncontrolled.json
  data/presets/highway/cycleway/crossing/unmarked.json
  data/presets/highway/footway/crossing/_marked.json
  data/presets/highway/footway/crossing/_zebra.json
  data/presets/highway/footway/crossing/traffic_signals.json
  data/presets/highway/footway/crossing/uncontrolled.json
  data/presets/highway/footway/crossing/unmarked.json
  interim/source_strings.yaml
Labels: enhancement

#737 Add translatable strings to substance field
  data/fields/substance.json
Labels: new-value

#735 Add translatable strings to material field
  data/fields/material.json
Labels: new-value

#734 Add translatable strings to memorial field
  data/fields/memorial.json
Labels: new-value

#709 Add translatable strings to barrier type field
  data/fields/barrier.json
Labels: new-value

#707 Add translatable strings to archaeological_site type field
  data/fields/archaeological_site.json
Labels: new-value

#744 Add fields for `parking:both|left|right` and `parking:both|left|right:orientation`
  data/fields/parking/side/orientation.json
  data/fields/parking/side/parking.json
  data/presets/highway/living_street.json
  data/presets/highway/primary.json
  data/presets/highway/primary_link.json
  data/presets/highway/residential.json
  data/presets/highway/service.json
  interim/source_strings.yaml
Labels: new-field

#672 fields/parking: Add options to harmonize centerline tagging
  data/fields/parking.json
Labels: new-value

#755 Make natural wood points unsearchable
  data/presets/natural/_wood.json
  data/presets/natural/wood.json
Labels: enhancement

#711 Add field for `lift_gate:type`
  data/fields/lift_gate/type.json
  data/presets/barrier/lift_gate.json
Labels: new-field

#747 Add translatable strings to sport field
  data/fields/sport.json
Labels: new-value

#758 Add translatable strings to waste field
  data/fields/waste.json
Labels: new-value

#761 Add translatable strings to office field
  data/fields/office.json
Labels: new-value

#760 Add translatable strings to resource field
  data/fields/resource.json
Labels: new-value

#763 Add translatable strings to clothes field
  data/fields/clothes.json
Labels: new-value

#764 Add translatable strings to building field
  data/fields/building.json
Labels: new-value

#766 Add `ref` field to Sports Pitch preset
  data/presets/leisure/pitch.json
Labels: add-field

#767 Create engineer.json
  data/presets/office/engineer.json
Labels: new-preset
