Repository openstreetmap/id-tagging-schema, pull requests merged in 2023-06, with the labels that each got.

#913 Add `maxstay` field to Charging Station preset
  data/presets/amenity/charging_station.json
Labels: add-field

#915 Added "it office" as term for `office=it`
  data/presets/office/it.json
Labels: new-label

#917 Add EV Charging Stall preset
  data/presets/amenity/charging_station.json
  data/presets/man_made/charge_point.json
Labels: new-preset

#926 Add Milk Churn Stand preset
  data/presets/man_made/milk_churn_stand.json
Labels: new-preset

#927 Allow Drinking Water preset on vertices
  data/presets/amenity/drinking_water.json
Labels: bug

#924 Add translatable strings to tomb field
  data/fields/tomb.json
Labels: new-value

#923 Add translatable strings to vending field
  data/fields/vending.json
Labels: new-value

#938 Use more common names for Trash Can/Recycling Bin presets
  data/presets/amenity/recycling_container.json
  data/presets/amenity/waste_basket.json
Labels: new-label

#939 Change ramp field to combo
  data/fields/ramp.json
Labels: enhancement, field

#933 Add translatable strings to telecom field
  data/fields/telecom.json
Labels: new-value
