Repository openstreetmap/id-tagging-schema, pull requests merged in 2023-03, with the labels that each got.

#804 UK specific Post Box tagging.
  data/fields/post_box/type.json
  data/fields/royal_cypher.json
  data/presets/amenity/post_box.json
  data/presets/amenity/post_box/post_box-GB.json
Labels: regional, new-field

#803 Add field 'website:menu'
  data/fields/website/menu.json
  data/presets/amenity/biergarten.json
  data/presets/amenity/cafe.json
  data/presets/amenity/fast_food.json
  data/presets/amenity/food_court.json
  data/presets/amenity/ice_cream.json
  data/presets/amenity/pub.json
  data/presets/amenity/restaurant.json
  interim/source_strings.yaml
Labels: new-field

#805 Remove postbox:type=community
  data/fields/post_box/type.json
Labels: considering

#807 Update deprecated.json
  data/deprecated.json
Labels: deprecating

#792 Update danger_area.json
  data/presets/landuse/military/_danger_area_point.json
  data/presets/landuse/military/danger_area.json
Labels: considering, new-label

#811 "dog groomer"/"cat groomer" should find "pet groomer", probably
  data/presets/shop/pet_grooming.json
Labels: new-label

#815 add korean and spanish restaurants
  data/presets/amenity/restaurant/korean.json
  data/presets/amenity/restaurant/spanish.json
Labels: new-preset

#813 Add translatable strings to historic field
  data/fields/historic.json
Labels: new-value

#814 remove disputed deprecation
  dist/deprecated.json
Labels: bug, deprecating

#800 Automated preview instances of iD for tagging PRs
  .github/workflows/build-preview.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  .nvmrc
  package-lock.json
Labels: enhancement, ci

#810 Add preset for man_made=quay
  data/fields/mooring.json
  data/presets/man_made/pier.json
  data/presets/man_made/quay.json
  interim/source_strings.yaml
Labels: new-preset, new-field

#817 Add Track & Field presets
  data/fields/athletics_pitch.json
  data/fields/athletics_track.json
  data/fields/sport.json
  data/fields/sport_racing_nonmotor.json
  data/presets/leisure/pitch/_athletics.json
  data/presets/leisure/pitch/athletics/discus_throw.json
  data/presets/leisure/pitch/athletics/hammer_throw.json
  data/presets/leisure/pitch/athletics/high_jump.json
  data/presets/leisure/pitch/athletics/javelin_throw.json
  data/presets/leisure/pitch/athletics/long_jump.json
  data/presets/leisure/pitch/athletics/pole_vault.json
  data/presets/leisure/pitch/athletics/shot_put.json
  data/presets/leisure/pitch/athletics/triple_jump.json
  data/presets/leisure/track/_athletics.json
  data/presets/leisure/track/athletics/_running.json
  data/presets/leisure/track/athletics/javelin_throw.json
  data/presets/leisure/track/athletics/long_jump.json
  data/presets/leisure/track/athletics/pole_vault.json
  data/presets/leisure/track/athletics/sprint.json
  data/presets/leisure/track/athletics/steeplechase.json
  data/presets/leisure/track/athletics/triple_jump.json
Labels: new-preset, new-field

#812 Update sport.json
  data/fields/sport.json
Labels: deprecating, new-value

#816 add preset for natural=peninsula
  data/presets/natural/peninsula.json
  interim/source_strings.yaml
Labels: new-preset

#806 Add emergency=fire_service_inlet
  data/fields/fire_mains.json
  data/fields/fire_service_inlet.json
  data/fields/fire_sprinkler.json
  data/presets/emergency/fire_service_inlet.json
Labels: new-preset, new-field

#827 Add flashing lights field to crossing=uncontrolled
  data/presets/highway/crossing/uncontrolled.json
Labels: add-field

#829 Avoid lowercasing Destination field on one-ways
  data/fields/destination_oneway.json
Labels: bug

#823 add hobby term to shop=anime
  data/presets/shop/anime.json
Labels: new-label

#821 make shop=hobby unsearchable
  data/presets/shop/_hobby.json
Labels: deprecating

#825 Readme: Extend translation section
  README.md
Labels: documentation

#830 Updated utility pole preset and add relevant deprecations
  data/deprecated.json
  data/presets/man_made/utility_pole.json
Labels: deprecating

#844 Improvements for peninsula preset
  data/presets/natural/cape.json
  data/presets/natural/peninsula.json
Labels: new-icon, new-label

#836 Add preset for Scout Group
  data/presets/club/scout.json
Labels: new-preset, new-field

#841 Add translatable strings to diplomatic field
  data/fields/diplomatic.json
Labels: new-value

#843 Add translatable strings to consulate field
  data/fields/consulate.json
Labels: new-value

#849 better castle icon
  data/presets/historic/castle.json
Labels: new-icon
