Repository openstreetmap/id-tagging-schema, pull requests merged in 2024-11, with the labels that each got.

#1371 Update vending.json, added e-cigarettes
  data/fields/vending.json
Labels: new-value

#1373 Specify values for tactile_map tag, add deprecations for map_type=tactile*
  data/deprecated.json
  data/fields/map_type.json
Labels: deprecating, new-value

#1370 add search terms to several presets
  data/presets/amenity/boat_rental.json
  data/presets/amenity/motorcycle_parking.json
  data/presets/amenity/telephone.json
  data/presets/barrier/height_restrictor.json
  data/presets/barrier/motorcycle_barrier.json
  data/presets/emergency/life_ring.json
  data/presets/emergency/phone.json
  data/presets/landuse/aquaculture.json
  data/presets/man_made/storage_tank.json
  data/presets/man_made/watermill.json
  data/presets/public_transport/platform/train.json
  data/presets/shop/motorcycle.json
  data/presets/shop/motorcycle_repair.json
  data/presets/tourism/theme_park.json
  data/presets/tourism/viewpoint.json
Labels: new-label

#1218 Add presets for `meadow=meadow_orchard`, `orchard=meadow_orchard`
  data/presets/landuse/meadow_orchard/meadow.json
  data/presets/landuse/meadow_orchard/orchard.json
Labels: regional, new-preset

#1309 Guidelines: Clarify rules for deprecations
  GUIDELINES.md
Labels: documentation

#1318 Docs/Guidelines: Improve "Purpose" section
  GUIDELINES.md
Labels: documentation
