Repository openstreetmap/id-tagging-schema, pull requests merged in 2024-04, with the labels that each got.

#1192 Add "E5 gasoline" as option to Fuel field
  data/fields/fuel/fuel_multi.json
Labels: new-value

#1182 Add terms to Dance Hall / Dance School presets
  data/presets/leisure/dance.json
  data/presets/leisure/dancing_school.json
Labels: new-label

#1163 A few dedicated icons suggestions
  data/presets/advertising/column.json
  data/presets/amenity/food_court.json
  data/presets/golf/tee.json
  data/presets/leisure/fitness_station/horizontal_ladder.json
  data/presets/leisure/fitness_station/rings.json
  data/presets/playground/hopscotch.json
  data/presets/public_transport/station_bus.json
  data/presets/public_transport/station_ferry.json
  data/presets/public_transport/station_light_rail.json
  data/presets/public_transport/station_monorail.json
  data/presets/public_transport/station_subway.json
  data/presets/public_transport/station_train.json
  data/presets/public_transport/station_tram.json
  data/presets/railway/_station.json
  data/presets/shop/mall.json
Labels: new-icon

#1181 Add terms to `historic = wayside_cross` preset
  data/presets/historic/wayside_cross.json
Labels: new-label

#1197 Add activity field to route_marker.json
  data/presets/tourism/information/route_marker.json
Labels: add-field
