Repository openstreetmap/id-tagging-schema, pull requests merged in 2024-02, with the labels that each got.

#1095 Add preset amenity=dog_toilet
  data/presets/amenity/dog_toilet.json
Labels: new-preset

#1037 Add Library Book Return preset
  data/presets/amenity/library_dropoff.json
Labels: new-preset

#1008 Add translatable strings for Swimming Pool field
  data/deprecated.json
  data/fields/swimming_pool.json
  data/presets/leisure/hot_tub.json
Labels: deprecating, new-preset, new-value

#1104 Deprecate `tourism=picnic_table` (-> `leisure=picnic_table`)
  data/deprecated.json
Labels: deprecating

#1103 Deprecate `tourism=resort` (-> `leisure=resort`)
  data/deprecated.json
Labels: deprecating

#1098 Deprecate `emergency=lifeguard_*` (-> `emergency=lifeguard` + `lifeguard=*`)
  data/deprecated.json
Labels: deprecating

#1109 Deprecate ```amenity=emergency_service```,```emergency=ses_station```,```emergency_service=technical``` -> ```emergency=disaster_response```
  data/deprecated.json
Labels: deprecating

#1105 Deprecate ```industrial=brickworks``` -> ```industrial=brickyard```
  data/deprecated.json
Labels: deprecating

#1108 add emergency=disaster_response preset
  data/presets/emergency/disaster_response.json
Labels: new-preset

#1116 feat: Add menstrual products
  data/fields/toilets/menstrual_products.json
  data/presets/amenity/toilets.json
Labels: new-field

#1102 Deprecate `leisure=maze` (-> `attraction=maze`)
  data/deprecated.json
Labels: waitfor-consensus, deprecating

#1124 Deprecate amenity=lockers
  data/deprecated.json
Labels: deprecating

#1135 Create preset for kitchen garden
  data/presets/leisure/garden/kitchen.json
Labels: new-preset

#1130 fix LPG/LNG confusion
  data/fields/fuel/fuel_multi.json
Labels: bug, new-value

#1129 add field for `fortification_type`
  data/fields/fortification_type.json
  data/presets/historic/archaeological_site.json
Labels: new-field

#1128 add structure field to steps preset
  data/presets/highway/steps.json
Labels: add-field

#1127 add road-related fields to busway preset
  data/presets/highway/busway.json
Labels: add-field

#1134 Add historic=cannon
  data/presets/historic/cannon.json
Labels: new-preset

#1126 add `via` tag to ferry routes
  data/presets/route/ferry.json
Labels: add-field

#1002 Add translatable strings to bridge field
  data/fields/bridge_combo.json
Labels: new-value

#1142 make this POI more findable
  data/presets/amenity/vending_machine/public_transport_tickets.json
Labels: new-label

#1032 #1016 Create bicycle_wash.json (amenity=bicycle_wash)
  data/presets/amenity/bicycle_wash.json
Labels: new-preset
