Repository openstreetmap/id-tagging-schema, pull requests merged in 2025-02, with the labels that each got.

#1434 upgrade to upload-artifact v4
  .github/workflows/build-preview.yml
Labels: ci

#1433 Add "addr:town" to address keys
  data/fields/address.json
Labels: new-value

#1232 Add cycle_barrier fields
  data/fields/cycle_barrier.json
  data/fields/cycle_barrier/installation.json
  data/fields/deflection.json
  data/fields/maxwidth/physical.json
  data/fields/opening.json
  data/fields/overlap.json
  data/fields/spacing.json
  data/presets/barrier/cycle_barrier.json
Labels: new-preset

#1320 Add field for `irrigation=pivot`
  data/fields/irrigation_pivot.json
  data/presets/landuse/farmland.json
Labels: new-field

#1446 add `entrance=shop` value also to values of entrance type field
  data/fields/entrance.json
Labels: new-value

#1449 add clear call to send PRs
  CONTRIBUTING.md
Labels: documentation

#1454 Add toilets as suggested tag for fast food places
  data/presets/amenity/fast_food.json
Labels: add-field

#1451 Add preset for amenity=veterinary_pharmacy
  data/presets/amenity/veterinary_pharmacy.json
Labels: new-preset

#1430 add shop-bbq preset
  data/presets/shop/bbq.json
Labels: new-preset
