Repository openstreetmap/id-tagging-schema, pull requests merged in 2025-09, with the labels that each got.

#1698 Add charging point terms to charging station
  data/presets/amenity/charging_station.json
  data/presets/man_made/charge_point.json
Labels: category-related

#1710 Add icon to fitness parallel bars preset
  data/presets/leisure/fitness_station/parallel_bars.json
Labels: new-label

#1004 Add translatable strings to playground field
  data/fields/playground.json
Labels: new-value, waiting-ready-to-merge

#1611 Add preset for `device_charging_station`
  data/presets/amenity/device_charging_station.json
Labels: new-preset, waiting-ready-to-merge

#1693 Add Ceremonial Gate and related presets
  data/deprecated.json
  data/fields/ceremonial_gate.json
  data/presets/man_made/ceremonial_gate.json
  data/presets/man_made/ceremonial_gate/paifang.json
  data/presets/man_made/ceremonial_gate/torii.json
  data/presets/man_made/torii.json
Labels: new-preset

#1517 Add Fish Farm / Hatchery preset and `aquaculture=*` field
  data/presets/landuse/aquaculture.json
  data/presets/landuse/aquaculture/fish.json
Labels: new-preset

#1660 Add term "street fitness" for `leisure=fitness_station` preset
  data/presets/leisure/fitness_station.json
Labels: new-label

#1524 Add option `container` to `building`field
  data/fields/building.json
Labels: field

#1506 Docs: Update wording "Data item", "OSM Wiki data item"
  CONTRIBUTING.md
  GUIDELINES.md
Labels: documentation

#1255 CI: Configure dependabot to update package.json
  .github/dependabot.yml
Labels: ci
