Repository openstreetmap/id-tagging-schema, pull requests merged in 2025-06, with the labels that each got.

#1576 make social_facility more findable
  data/presets/amenity/social_facility.json
Labels: new-label

#1575 Add `direction` field to Observation Tower preset
  data/presets/man_made/tower/observation.json
Labels: add-field, waiting-ready-to-merge

#1552 Add roof shape and roof height fields to building presets
  data/fields/roof/height.json
  data/fields/roof/shape.json
  data/presets/building.json
  data/presets/building/roof.json
  data/presets/building_part.json
Labels: new-field, waiting-ready-to-merge

#1604 Add term "solicitor" to lawyer preset
  data/presets/office/lawyer.json
Labels: new-label

#1598 Add preset for `climbing=route` point, way and relation
  data/preset_categories/climbing.json
  data/preset_categories/route.json
  data/presets/climbing/route.json
  data/presets/type/route/climbing.json
Labels: new-preset, waiting-ready-to-merge

#1587 Add bridge to the structure field of canal
  data/fields/structure_canal.json
  data/presets/waterway/canal.json
Labels: field, waiting-ready-to-merge

#1619 Add terms to `shop=fabric`
  data/presets/shop/fabric.json
Labels: new-label
